### ISSUE TITLE
A couple questions.

### ISSUE THREAD

**Issue by rippin** [crexi-dev/sdet-assignment#2]
**Property Details: Users can click on a property to view its details.**

For the property details test I need a little more clarification.

So should users just be able to click on any property and view the details? 

As in search for a random property and click on it to view the details?

Also are all the fields under details required?

**Search: Users can search for properties based on different criteria (pick one)**

For this do you mean picking one search filter and just submitting a search?

Thanks in advance

**Comment by sviataslau** [comment]
Great questions!

> So should users just be able to click on any property and view the details?
> As in search for a random property and click on it to view the details?

Yep, as simple as that

> Also are all the fields under details required?

That's a great question. Well, there are many fields; some of them are required, and some of them are not. I would say, we'd focus on verifying that we opened the right property and its data matches the one you see on the search result list.

> For this do you mean picking one search filter and just submitting a search?

Yep, submit the search and verify it was successful (ideally, you find a way to make sure the properties returned match the filter)
